function createfigure(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%CREATEFIGURE1(X1, YMatrix1, YMatrix2, YMatrix3, YMatrix4)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  YMATRIX2:  matrix of plot y data
%  YMATRIX3:  matrix of plot y data
%  YMATRIX4:  matrix of plot y data

%  Auto-generated by MATLAB on 07-Dec-2022 19:58:00

% Create figure
figure1 = figure('WindowState','maximized');

% Create subplot
subplot1 = subplot(4,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1,'LineWidth',2);
set(plot1(1),'DisplayName','MPC');
set(plot1(2),'DisplayName','ideal');

% Create ylabel
ylabel('f_1 (N)','FontWeight','bold','FontName','Arial');

box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontName','Arial','FontSize',12,'LineWidth',1.5);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'EdgeColor',[0 0 0]);

% Create subplot
subplot2 = subplot(4,2,3,'Parent',figure1);
hold(subplot2,'on');

% Create multiple line objects using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',2);
set(plot2(1),'DisplayName','MPC');
set(plot2(2),'DisplayName','ideal');

% Create ylabel
ylabel('f_2 (N)','FontWeight','bold','FontName','Arial');

box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'FontName','Arial','FontSize',12,'LineWidth',1.5);
% Create legend
legend(subplot2,'show');

% Create subplot
subplot3 = subplot(4,2,5,'Parent',figure1);
hold(subplot3,'on');

% Create multiple line objects using matrix input to plot
plot3 = plot(X1,YMatrix3,'Parent',subplot3,'LineWidth',2);
set(plot3(1),'DisplayName','MPC');
set(plot3(2),'DisplayName','ideal');

% Create ylabel
ylabel('f_3 (N)','FontWeight','bold','FontName','Arial');

box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'FontName','Arial','FontSize',12,'LineWidth',1.5);
% Create legend
legend(subplot3,'show');

% Create subplot
subplot4 = subplot(4,2,7,'Parent',figure1);
hold(subplot4,'on');

% Create multiple line objects using matrix input to plot
plot4 = plot(X1,YMatrix4,'Parent',subplot4,'LineWidth',2);
set(plot4(1),'DisplayName','MPC');
set(plot4(2),'DisplayName','ideal');

% Create ylabel
ylabel('f_4 (N)','FontWeight','bold','FontName','Arial');

% Create xlabel
xlabel('time (s)','FontWeight','bold','FontSize',12);

box(subplot4,'on');
hold(subplot4,'off');
% Set the remaining axes properties
set(subplot4,'FontName','Arial','FontSize',12,'LineWidth',1.5);
% Create legend
legend2 = legend(subplot4,'show');
set(legend2,...
    'Position',[0.415277778274483 0.218421644884768 0.0432291661699611 0.0399792305158059]);

% Create axes
axes('Parent',figure1);
axis off

% Create xlabel
xlabel('time (s)','FontWeight','bold','FontSize',12,'FontName','Arial',...
    'Visible','on');

